# ProStreet Time Trial Ghosts by Chloe @gaycoderprincess
# enjoy, nya~ :3

tank_unslapper = true	# removes the steering delay (warning: this changes the ghosts you race against!)

gas_pedal_hack = false	# adds an anti-deadzone of 10% to the gas pedal, random hack for personal use